INSERT INTO veiculos (marca, modelo, cor, placa, tipo) VALUES
('Volkswagen', 'Gol', 'Branco', 'ABC1D23', 'CARRO'),
('Fiat', 'Uno', 'Vermelho', 'DEF4G56', 'CARRO'),
('Chevrolet', 'Onix', 'Prata', 'GHI7J89', 'CARRO'),
('Honda', 'CG 160', 'Preto', 'JKL0M12', 'MOTO'),
('Yamaha', 'Fazer 250', 'Azul', 'MNO3P45', 'MOTO'),
('Ford', 'Ka', 'Verde', 'PQR6S78', 'CARRO'),
('Toyota', 'Corolla', 'Cinza', 'STU9V01', 'CARRO'),
('BMW', 'GS 310', 'Branco', 'VWX2Y34', 'MOTO'),
('Hyundai', 'HB20', 'Prata', 'YZA5B67', 'CARRO'),
('Suzuki', 'Burgman 125', 'Vermelho', 'BCD8E90', 'MOTO'),
('Renault', 'Kwid', 'Amarelo', 'EFG1H23', 'CARRO'),
('Kawasaki', 'Ninja 300', 'Verde', 'HIJ4K56', 'MOTO'),
('Jeep', 'Renegade', 'Laranja', 'KLM7N89', 'CARRO'),
('Dafra', 'Citycom 300', 'Preto', 'NOP0Q12', 'MOTO'),
('Nissan', 'Kicks', 'Branco', 'QRS3T45', 'CARRO'),
('Harley-Davidson', 'Street 750', 'Preto', 'TUV6W78', 'MOTO'),
('Citroën', 'C3', 'Azul', 'WXY9Z01', 'CARRO'),
('Ducati', 'Monster 797', 'Vermelho', 'ZAB2C34', 'MOTO'),
('Peugeot', '208', 'Cinza', 'CDE5F67', 'CARRO'),
('Triumph', 'Bonneville', 'Preto', 'FGH8I90', 'MOTO');